# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Find
find_keyword = { fg = "#f7768e", bold = true, italic = true, underline = true }
find_position = { fg = "#f7768e", bold = true, italic = true }

# Marker
marker_copied = { fg = "#4e7b1e", bg = "#4e7b1e" }
marker_cut = { fg = "#4e7b1e", bg = "#4e7b1e" }
marker_marked = { fg = "#f7768e", bg = "#f7768e" }
marker_selected = { fg = "#9ece6a", bg = "#9ece6a" }

# Count
count_copied = { fg = "#ffffff", bg = "#4e7b1e" }
count_cut = { fg = "#ffffff", bg = "#4e7b1e" }
count_selected = { fg = "#e6e1e5", bg = "#9ece6a" }

# Border
border_style  = { fg = "#7aa2f7" }

# : ]]]


# : Status [[[

[status]
overall = { fg = "#7aa2f7" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#7aa2f7", bg = "#1a1b26" }
progress_error = { fg = "#f7768e", bg = "#1a1b26" }

# Permissions
perm_type = { fg = "#bb9af7" }
perm_write = { fg = "#9ece6a" }
perm_exec = { fg = "#f7768e" }
perm_read = { fg = "#4e7b1e" }
perm_sep = { fg = "#013198" }

# : ]]]


# : Mode [[[

[mode]

normal_main = { bg = "#7aa2f7", fg = "#e6e1e5", bold = true }
normal_alt  = { bg = "#242635", fg = "#ffffff" }

select_main = { bg = "#bb9af7", fg = "#e6e1e5", bold = true }
select_alt  = { bg = "#242635", fg = "#ffffff" }

unset_main = { bg = "#9ece6a", fg = "#000000", bold = true }
unset_alt  = { bg = "#242635", fg = "#ffffff" }

# : ]]]


# : Input [[[

[input]
border = { fg = "#7aa2f7" }
title = {}
value = { fg = "#ffffff" }
selected = { reversed = true }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#7aa2f7", bold = true, bg = "#1a1b26" }
inactive = { fg = "#bb9af7", bg = "#1a1b26" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#7aa2f7", bg = "#e6e1e5" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#7aa2f7" }
title = {}
hovered = { fg = "#4e7b1e", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#1a1b26" }
cand = { fg = "#7aa2f7" }
rest = { fg = "#e6e1e5" }
desc = { fg = "#ffffff" }
separator = " ▶ "
separator_style = { fg = "#ffffff" }

# : ]]]

# : Spotter [[[

[spot]
border   = { fg = "#7aa2f7" }
title    = { fg = "#7aa2f7" }
tbl_col  = { fg = "#ffffff" }
tbl_cell = { fg = "#ffffff", bg = "#1a1b26" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#e6e1e5", bg = "#bb9af7" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#9ece6a" }
title_warn = { fg = "#7aa2f7" }
title_error = { fg = "#f7768e" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { mime = "*", is = "orphan", fg = "#ffffff", bg = "#98011d" },
    { mime = "application/*exec*", fg = "#f7768e" },

    # Fallback
    { url = "*", fg = "#ffffff" },
    { url = "*/", fg = "#7aa2f7" },
]

# : ]]]
