[colors]
background = '#111318'
foreground = '#e2e2e9'

cursor_bg = '#adc6ff'
cursor_fg = '#111318'
cursor_border = '#adc6ff'

selection_bg = '#2b4678'
selection_fg = '#e2e2e9'

ansi = ['#111318', '#e54d45', '#6fd66e', '#dbd27b', '#6180d1', '#8e9dbf', '#adc6ff', '#abb2bf']
brights = ['#5c6370', '#e0605f', '#86e086', '#e8e197', '#b9d4ff', '#517bac', '#6b75b3', '#ffffff']
